resources:
  repositories:
    - repository: templates
      type: github
      name: BMO-Prod/template_repo # name of the GitHub repository
      endpoint: GitHub
      ref: refs/tags/v1.1.0
steps:
- script: ansible-playbook ansible-playbook.yaml
  displayName: 'Run Ansible Playbook'