resources:
  repositories:
    - repository: templates
      type: github
      name: BMO-Prod/template_repo # name of the GitHub repository
      endpoint: github.com_alicegolakiya
#      ref: refs/tags/v1.1.0
stages:
- template: apic_dev.yaml
  parameters:
    agentPoolName: 'Prod'
    agentOS: 'Linux'
    defaultvarilables:
      __default__:
        anisbleUsername: 'sa_apicpubapp_dev'
        anisblePassword: '<Password here>'
        anisbleInventory: 'buildhost'
        anisbleJobTemplate: 
        anisbleApiHost: anisble.bmogc.net

